config/routes.rb
LocalSupport::Application.routes.draw do

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  get '/embedded/map' => 'volunteer_ops#embedded_map'

  get 'contributors' => 'contributors#show'
  match 'organisations/search' => 'organisations#search', via: [:get, :post]

  get '/organisation_reports/without_users' => 'organisation_reports#without_users_index', as: :organisations_report
  post '/invitations' => 'invitations#create', as: :invitations

  get '/user_reports/all' => 'user_reports#index', as: :users_report
  put '/user_reports/update' => 'user_reports#update', as: :user_report
  delete '/user_reports' => 'user_reports#destroy'
  get '/user_reports/invited' => 'user_reports#invited', as: :invited_users_report
  get '/user_reports/deleted' => 'user_reports#deleted', as: :deleted_users_report
  put 'user_reports/undo_delete/:id' => 'user_reports#undo_delete', as: :undo_delete_users_report

  resources :doit_organisations, only: [:index]
  resources :pages, only: [:index, :new, :create, :edit]
  resources :volunteer_ops, :only => [:index, :edit, :show, :update, :destroy] do
    get 'search', on: :collection
  end
  resources :proposed_organisation_edits, :only => [:index]
  resources :organisations do
    resources :volunteer_ops, :only => [:new, :create]
    resources :proposed_organisation_edits, :only => [:new, :show, :create, :update]
  end
  resources :users
  get 'events/search' => 'events#search'
  resources :events, :only => [:new, :create, :show, :index]
  resources :proposed_organisations, :only => [:new, :create, :show, :index, :update, :destroy]

  get ':id', to: 'pages#show', as: :page
  patch ':id', to: 'pages#update', as: nil
  delete ':id', to: 'pages#destroy', as: nil

  post 'cookies/allow', to: 'application#allow_cookie_policy'

  resources :mail_templates

  root :to => 'volunteer_ops#index'

end

app/models/proposed_organisation_edit.rb
require 'proposes_edits'
class ProposedOrganisationEdit < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :organisation
  belongs_to :editor, :class_name => "User", :foreign_key => "user_id"
  include ProposesEdits
  proposes_edits_to :organisation
  editable_fields :address, :name, :description, :postcode, :email, :website, :telephone, :donation_info
  publish_fields_booleans ->(f) {publish_fields_map(f)}
  non_public_fields_editable_by :siteadmin
  non_public_fields_viewable_by :siteadmin, :superadmin
  scope :still_pending, ->{where(archived: false)}

  private
  def self.publish_fields_map field
    if field == :telephone
      :publish_phone
    else
      ('publish_' + field.to_s).to_sym
    end
  end

end

app/controllers/proposed_organisation_edits_controller.rb
class ProposedOrganisationEditsController < ApplicationController

  before_action :authorize, :only => [:update]

  def new
    org = Organisation.friendly.find params[:organisation_id]
    @proposed_organisation_edit = ProposedOrganisationEdit.new organisation: org
  end

  def create
    org = Organisation.friendly.find(params[:organisation_id])
    create_params = proposed_edit_params.merge!(organisation: org, editor: current_user)
    proposed_org_edit = CreateProposedOrganisationEdit.with(self, create_params)
    redirect_to organisation_proposed_organisation_edit_path org, proposed_org_edit
  end

  def show
    @organisation = Organisation.friendly.find(params[:organisation_id])
    @proposed_organisation_edit = ProposedOrganisationEdit.find(params[:id])
  end

  def index
    @proposed_organisation_edits = ProposedOrganisationEdit.still_pending
  end

  def update
    # UpdateProposedOrganisationEdit.with(observer: self, params: create_params)
    proposed_edit = ProposedOrganisationEdit.find(update_params.fetch(:id))
    if proposed_edit_params.any?
      proposed_edit.accept(proposed_edit_params)
      flash[:notice] = "The edit you accepted has been applied and archived"
    else
      proposed_edit.update!(archived: true)
      flash[:notice] = "The edit you rejected has been archived"
    end
    redirect_to organisation_path proposed_edit.organisation
  end

  def set_notice(notice)
    flash[:notice] = notice
  end

  def update_params
    params.require(:proposed_organisation_edit).permit(:id)
  end

  def proposed_edit_params
    params.require(:proposed_organisation_edit).permit(
      :name,
      :description,
      :donation_info,
      :address,
      :postcode,
      :telephone,
      :website,
      :email,
    )
  end

  #  +-----+-----+
  #  |  1  |  2  |
  #  |     |     |
  #  +-----+-----+
  #  |  3  |  4  |
  #  |     |     |
  #  +-----+-----+
  #
  #  1. Not archived, not accepted ... what Rachel sees in "All proposed edits"
  #  2. Not archived, accepted ... invalid state
  #  3. archived, not accepted ... rejected edits
  #  4. archived, accepted ... accepted edits
end

app/helpers/proposed_organisation_edits_helper.rb
module ProposedOrganisationEditsHelper

  def show_class(mode, attr)
    classes = [mode + '_organisation_' + attr]
    if @proposed_organisation_edit.has_proposed_edit?(attr.to_sym)
      classes << (mode == 'current' ? 'current_value' : 'proposed_value')
    end
    classes.join(' ')
  end

end

app/views/proposed_organisation_edits/_form.html.erb
<%= form_for(setup_proposed_organisation_edit(@proposed_organisation_edit), url: organisation_proposed_organisation_edits_path(@proposed_organisation_edit.organisation)) do |f| %>
    <table class="centered" >
      <thead>
      </thead>
      <tbody>
      <tr>
        <td data-toggle="tooltip" title="Enter a unique name">
          <%= f.text_area :name, :size => "50x4", :class => "wide_form org_h3", :placeholder => "Enter organisation name" %>
        </td>
        <td class="borderless">
          <input type="checkbox" class="publish" disabled checked = "checked" value="">
        </td>
      </tr>
      <tr>
        <td class="borderless" data-toggle="tooltip" title="Enter a full description here. When an individual searches this database all words in this description will be searched.">
          <%= f.text_area :description, :class => "wide_form", :cols => "10", :rows => "10", :placeholder => "Enter organisation description" %>
        </td>
        <td class="borderless">
          <input type="checkbox" class="publish" disabled checked = "checked" value="">
        </td>
      </tr>
      <tr><td><h4>
        Contact information
      </h4></td></tr>
      <% if @proposed_organisation_edit.editable?(:address, by: current_user) %>
      <tr>
        <td data-toggle="tooltip" title="Enter a complete address">
          <%= f.text_field :address, :class => "wide_form", :placeholder => "Enter organisation address"%>
        </td>
        <td class="borderless">
          <input type="checkbox" disabled class="publish" <%= checked="checked" if @proposed_organisation_edit.viewable_field?(:address) %> value="" class="publish">
        </td>
      </tr>
      <% end %>
      <tr>
        <td class="borderless" data-toggle="tooltip" title="Make sure post code is accurate">
          <%= f.text_field :postcode, :class => "wide_form", :placeholder => "Enter organisation post code" %>
        </td>
        <td class="borderless">
          <input type="checkbox" class="publish" disabled checked = "checked" value="">
        </td>
      </tr>
      <% if @proposed_organisation_edit.editable?(:email, by: current_user)%>
      <tr>
        <td class="borderless" data-toggle="tooltip" title="Make sure email is correct">
          <%= f.text_field :email, :class => "wide_form", :placeholder => "Enter organisation email address" %>
        </td>
        <td class="borderless">
          <input type="checkbox" disabled class="publish" <%= checked="checked" if @proposed_organisation_edit.viewable_field?(:email) %> value="" class="publish">
        </td>
      </tr>
      <% end %>
      <tr>
        <td class="borderless" data-toggle="tooltip" title="Make sure url is correct">
          <%= f.text_field :website, :class => "wide_form", :placeholder => "Enter organisation website url" %>
        </td>
        <td class="borderless">
          <input type="checkbox" class="publish" disabled checked = "checked" value="">
        </td>
      </tr>
      <% if @proposed_organisation_edit.editable?(:telephone, by: current_user)%>
      <tr>
        <td class="borderless" data-toggle="tooltip" title="Make sure phone number is correct">
          <%= f.text_field :telephone, :class => "wide_form", :placeholder => "Enter organisation phone number" %>
        </td>
        <td class="borderless">
          <input type="checkbox" disabled class="publish" <%= checked="checked" if @proposed_organisation_edit.viewable_field?(:telephone) %> value="" class="publish">
        </td>
      </tr>
      <% end %>
      <tr>
        <td class="borderless" data-toggle="tooltip" title="Please enter a website here either to the fundraising page on your website or to an online donation site.">
          <%= f.text_field :donation_info, :class => "wide_form", :placeholder => "Enter organisation donation url" %>
        </td>
        <td class="borderless">
          <input type="checkbox" disabled checked = "checked" value="" class="publish">
        </td>
      </tr>
      <tr>
        <td style="padding-top: 5px;"><%= f.submit "Propose this edit",:class => 'btn btn-primary' %></td>
        <td></td>
      </tr>
      </tbody>
    </table>

<% end %>

app/views/proposed_organisation_edits/index.html.erb
<div class="well">
  <table class="table table-responsive table-hover sortable">
    <thead>
    <tr>
      <th>Editor Email</th>
      <th>Proposed </th>
      <th>Last modified</th>
      <th>Organisation to be edited</th>
      <th> </th>
    </tr>
    </thead>
    <% @proposed_organisation_edits.each do |proposed_edit| %>
        <tr id="<%= proposed_edit.id %>" class="actions-right">
          <td><%= proposed_edit.editor.try(:email) %></td>
          <td><%= time_ago_in_words_with_nils(proposed_edit.try(:created_at)) %> </td>
          <td><%= time_ago_in_words_with_nils(proposed_edit.try(:updated_at)) %></td>
          <td><%= proposed_edit.organisation.name %></td>
          <td>
            <%= link_to(organisation_proposed_organisation_edit_path(proposed_edit.organisation, proposed_edit),
                        :class => "btn btn-small btn-primary pull-right") do %>
                <i class="fa fa-undo"></i> View Details</a>
            <% end %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/proposed_organisation_edits/new.html.erb
<%= render 'form' %>

app/views/proposed_organisation_edits/show.html.erb
<% if @proposed_organisation_edit.editor %>
<div class="centered width_50 proposer">
  <span>This edit proposed by:</span>
  <%= @proposed_organisation_edit.editor.email%>
</div>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h3 class="text-center">Current Information</h3>
    <h4 class="<%= show_class('current', 'name') %>">
      <span class='field_value'>
      <%= @organisation.name %>
      </span>
    </h4>
    <p>
      <%= simple_format @organisation.description, class: show_class('current', 'description') %>
    </p>
    <% if @proposed_organisation_edit.viewable_field?(:address, by: current_user) %>
      <p class="<%= show_class('current', 'address') %>">
        <span><b>Address:</b></span>
        <span class='field_value'>
          <%= @organisation.address %>
        </span>
      </p>
    <% end %>

    <% if @proposed_organisation_edit.editable? :postcode  %>
        <p class="<%= show_class('current', 'postcode') %>">
          <span><b>Postcode:</b></span>
          <span class='field_value'>
            <%= @organisation.postcode %>
          </span>
        </p>
    <% end %>

    <% if @proposed_organisation_edit.viewable_field?(:email, by: current_user)%>
        <p class="<%= show_class('current', 'email') %>">
          <span><b>Email:</b></span>
          <span class='field_value'>
            <a href="mailto:<%= @organisation.email %>"><%= @organisation.email %></a>
          </span>
        </p>
    <% end %>

    <% if @proposed_organisation_edit.editable? :website %>
      <p class="<%= show_class('current', 'website') %>">
        <span><b>Website:</b></span>
        <span class='field_value'>
          <%= link_to @organisation.website, @organisation.website, {:target => '_blank'} if @organisation.website.present?%>
        </span>
      </p>
    <% end %>

    <% if @proposed_organisation_edit.viewable_field?(:telephone, by: current_user)%>
      <p class="<%= show_class('current', 'telephone') %>">
      <span><b>Telephone:</b></span>
      <span class='field_value'>
        <%= @organisation.telephone %>
      </span>
      </p>
    <% end %>

    <% if @proposed_organisation_edit.editable?(:donation_info)  %>
        <p class="<%= show_class('current', 'donation_info') %>">
        <span><b>Donation Info:</b></span>
          <span class='field_value'>
            <%= @organisation.donation_info %>
          </span>
        </p>
    <% end %>

    <% if current_user.try(:superadmin?) %>
        <div class="centered width_25">
          <%= form_for([@proposed_organisation_edit.organisation, @proposed_organisation_edit], :url => {:action => :update}) do |f| %>
            <%= f.hidden_field :id, value: @proposed_organisation_edit.id %>
            <%= f.submit 'Keep Current Information', :class => 'btn btn-primary' %>
          <% end %>
        </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <h3 class="text-center">Proposed Edit</h3>
    <h4 class="<%= show_class('proposed', 'name') %>">
      <span class="field_value">
      <%= @proposed_organisation_edit.name %>
      </span>
    </h4>
    <p>
      <span class="field_value">
      <%= simple_format @proposed_organisation_edit.description, class: show_class('proposed', 'description') %>
      </span>
    </p>

    <% if @proposed_organisation_edit.viewable_field?(:address, by: current_user) %>
      <p class="<%= show_class('proposed', 'address') %>">
        <span><b>Address:</b></span>
        <span class='field_value'>
          <%= @proposed_organisation_edit.address %>
        </span>
      </p>
    <% end %>

    <% if @proposed_organisation_edit.editable? :postcode %>
        <p class="<%= show_class('proposed', 'postcode') %>">
          <span><b>Postcode:</b></span>
          <span class='field_value'>
            <%= @proposed_organisation_edit.postcode %>
          </span>
        </p>
    <% end %>

    <% if @proposed_organisation_edit.viewable_field?(:email, by: current_user) %>
      <p class="<%= show_class('proposed', 'email') %>">
        <span><b>Email:</b></span>
        <span class='field_value'>
          <a href="mailto:<%= @proposed_organisation_edit.email %>"><%= @proposed_organisation_edit.email %></a>
        </span>
      </p>
    <% end %>

    <% if @proposed_organisation_edit.editable? :website %>
      <p class="<%= show_class('proposed', 'website') %>">
        <span><b>Website:</b></span>
        <span class='field_value'>
          <%= link_to @proposed_organisation_edit.website, @proposed_organisation_edit.website, {:target => '_blank'} if @proposed_organisation_edit.website.present?%>
        </span>
      </p>
    <% end %>

    <% if @proposed_organisation_edit.viewable_field?(:telephone, by: current_user) %>
        <p class="<%= show_class('proposed', 'telephone') %>">
          <span><b>Telephone:</b></span>
          <span class='field_value'>
            <%= @proposed_organisation_edit.telephone %>
          </span>
        </p>
    <% end %>

    <% if @proposed_organisation_edit.editable? :donation_info %>
        <p class="<%= show_class('proposed', 'donation_info') %>">
          <span><b>Donation Info:</b></span>
          <span class='field_value'>
            <%= @proposed_organisation_edit.donation_info %>
          </span>
        </p>
    <% end %>

    <% if current_user.try(:superadmin?) %>
        <div class="centered width_25">
          <%= form_for([@proposed_organisation_edit.organisation, @proposed_organisation_edit], :url => {:action => :update}) do |f| %>
            <%= f.hidden_field :id, value: @proposed_organisation_edit.id %>
            <%= f.hidden_field :name, value: @proposed_organisation_edit.name %>
            <%= f.hidden_field :description, value: @proposed_organisation_edit.description %>
            <%= f.hidden_field :donation_info, value: @proposed_organisation_edit.donation_info %>
            <% if @proposed_organisation_edit.editable?(:address, by: @proposed_organisation_edit.editor) %>
            <%= f.hidden_field :address, value: @proposed_organisation_edit.address %>
            <% end %>
            <%= f.hidden_field :postcode, value: @proposed_organisation_edit.postcode %>
            <% if @proposed_organisation_edit.editable?(:telephone, by: @proposed_organisation_edit.editor)%>
            <%= f.hidden_field :telephone, value: @proposed_organisation_edit.telephone %>
            <% end %>
            <%= f.hidden_field :website, value: @proposed_organisation_edit.website %>
            <% if @proposed_organisation_edit.editable?(:email, by: @proposed_organisation_edit.editor)%>
            <%= f.hidden_field :email, value: @proposed_organisation_edit.email %>
            <% end %>
            <%= f.submit 'Accept Edit', :class => 'btn btn-success' %>
          <% end %>
        </div>
    <% end %>
  </div>
</div>