config/routes.rb
LocalSupport::Application.routes.draw do

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  get '/embedded/map' => 'volunteer_ops#embedded_map'

  get 'contributors' => 'contributors#show'
  match 'organisations/search' => 'organisations#search', via: [:get, :post]

  get '/organisation_reports/without_users' => 'organisation_reports#without_users_index', as: :organisations_report
  post '/invitations' => 'invitations#create', as: :invitations

  get '/user_reports/all' => 'user_reports#index', as: :users_report
  put '/user_reports/update' => 'user_reports#update', as: :user_report
  delete '/user_reports' => 'user_reports#destroy'
  get '/user_reports/invited' => 'user_reports#invited', as: :invited_users_report
  get '/user_reports/deleted' => 'user_reports#deleted', as: :deleted_users_report
  put 'user_reports/undo_delete/:id' => 'user_reports#undo_delete', as: :undo_delete_users_report

  resources :doit_organisations, only: [:index]
  resources :pages, only: [:index, :new, :create, :edit]
  resources :volunteer_ops, :only => [:index, :edit, :show, :update, :destroy] do
    get 'search', on: :collection
  end
  resources :proposed_organisation_edits, :only => [:index]
  resources :organisations do
    resources :volunteer_ops, :only => [:new, :create]
    resources :proposed_organisation_edits, :only => [:new, :show, :create, :update]
  end
  resources :users
  get 'events/search' => 'events#search'
  resources :events, :only => [:new, :create, :show, :index]
  resources :proposed_organisations, :only => [:new, :create, :show, :index, :update, :destroy]

  get ':id', to: 'pages#show', as: :page
  patch ':id', to: 'pages#update', as: nil
  delete ':id', to: 'pages#destroy', as: nil

  post 'cookies/allow', to: 'application#allow_cookie_policy'

  resources :mail_templates

  root :to => 'volunteer_ops#index'

end

app/models/proposed_organisation.rb
class ProposedOrganisation < BaseOrganisation
  has_many :users, :foreign_key => 'organisation_id'
  
  def accept_proposal
    org = becomes!(Organisation)
    org.save!
    org
  end
end

app/controllers/proposed_organisations_controller.rb
class ProposedOrganisationsController < BaseOrganisationsController
  layout 'two_columns_with_map', except: [:index]
  before_action :require_superadmin_or_recent_creation, only: [:show]
  before_action :require_superadmin, only: [:update, :destroy]

  def index
    @proposed_organisations = ProposedOrganisation.all
  end

  def update
    rslt = prepare_data_for_update
    redirect_to organisation_path(rslt.accepted_org) and return false if rslt.accepted_org
    redirect_to proposed_organisations_path
  end

  def destroy
    proposed_org = ProposedOrganisation.friendly.find params[:id]
    proposed_org.destroy
    redirect_to proposed_organisations_path
  end

  def new
    @proposed_organisation = ProposedOrganisation.new 
    @user_id = session[:user_id] || current_user.try(:id)
  end

  def create
    make_user_into_org_admin_of_new_proposed_org
    if @proposed_organisation.save
      session[:proposed_organisation_id] = @proposed_organisation.id
      send_email_to_superadmin_about_org_signup @proposed_organisation
      redirect_to @proposed_organisation, notice: 'Organisation is pending admin approval.'
    else
      render :new
    end
  end

  def show
    @proposed_organisation = ProposedOrganisation.friendly.find(params[:id])
    proposed_organisations = ProposedOrganisation.where(id: @proposed_organisation.id)
    #refactor this into model
    @proposer_email = @proposed_organisation.users.first.email if !@proposed_organisation.users.empty?
    @markers = build_map_markers(proposed_organisations)
  end

  private
  
  def prepare_data_for_update
    proposed_org = ProposedOrganisation.friendly.find params[:id]
    rslt = AcceptProposedOrganisation.new(proposed_org).run
    flash.replace(CreateFlashForProposedOrganisation.new(rslt).run)
    rslt
  end

  def make_user_into_org_admin_of_new_proposed_org
    org_params = ProposedOrganisationParams.build params
    usr = User.find params[:proposed_organisation][:user_id] if params[:proposed_organisation][:user_id]
    @proposed_organisation = ProposedOrganisation.new(org_params)
    @proposed_organisation.users << [usr] if usr
  end

  def send_email_to_superadmin_about_org_signup(org)
    superadmin_emails = User.superadmins.pluck(:email)
    AdminMailer.new_org_waiting_for_approval(org, superadmin_emails).deliver_now
  end

  def require_superadmin
    unless current_user.try(:superadmin?)
      flash[:warning] = PERMISSION_DENIED
      redirect_to root_path and return false
    end
  end

  def require_superadmin_or_recent_creation
    unless session[:proposed_organisation_id] || current_user.try(:superadmin)
      flash[:notice] = PERMISSION_DENIED
      redirect_to root_path
    end
  end
end

class ProposedOrganisationParams
  def self.build params
    params.require(:proposed_organisation).permit(
      :superadmin_email_to_add,
      :description,
      :address,
      :publish_address,
      :postcode,
      :email,
      :publish_email,
      :website,
      :publish_phone,
      :donation_info,
      :name,
      :telephone,
      :non_profit,
      :works_in_harrow,
      :registered_in_harrow,
      category_ids: []
    )
  end
end

app/views/proposed_organisations/index.html.erb
<div class="well">
  <table class="table table-responsive table-hover sortable">
    <thead>
    <tr>
      <th>Proposer Email</th>
      <th>Proposed </th>
      <th>Last modified</th>
      <th>Organisation Name</th>
      <th> </th>
    </tr>
    </thead>
    <% @proposed_organisations.each do |proposed_organisation| %>
        <tr id="<%= proposed_organisation.id %>" class="actions-right">
          <td><%= proposed_organisation.users.first.try(:email) %></td>
          <td><%= time_ago_in_words_with_nils(proposed_organisation.try(:created_at)) %> </td>
          <td><%= time_ago_in_words_with_nils(proposed_organisation.try(:updated_at)) %></td>
          <td><%= proposed_organisation.name %></td>
          <td>
            <%= link_to(proposed_organisation_path(proposed_organisation),
                        :class => "btn btn-small btn-primary pull-right") do %>
                <i class="fa fa-undo"></i> View Details</a>
            <% end %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/proposed_organisations/new.html.erb
<%= render partial: 'organisations/form', locals: {org: @proposed_organisation} %>

app/views/proposed_organisations/show.html.erb
<div class="org-information">
  <% if @proposer_email %>
    <p>
      This organisation proposed by '<%= @proposer_email%>'
    </p>
  <% end %>
  <%= render partial: "organisations/show", locals: {org: @proposed_organisation}%>
  <br>
  <strong>Eligibility:</strong>
  <ul class="list-unstyled" style="text-indent: 10px;">
    <% if @proposed_organisation.non_profit %>
      <li>We are a not for profit organisation registered or working in Harrow</li>
    <% end %>
  </ul>

  <% if current_user.try(:superadmin?) %>
    <%= form_for((@proposed_organisation), :url => {:action => :update}, :html =>
        {:style => 'display: inline-block;'}) do |f| %>
      <%= f.submit 'Accept', :class => 'btn btn-primary' %>
    <% end %>
    <%= form_for((@proposed_organisation), :method => :delete, :html =>
        {:style => 'display: inline-block;'}) do |f| %>
      <%= f.submit 'Reject', :class => 'btn btn-danger' %>
    <% end %>
  <% end %>
</div>

<% render partial: 'shared/map_scripts', locals: {markers: @markers} %>