config/routes.rb
LocalSupport::Application.routes.draw do

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  get '/embedded/map' => 'volunteer_ops#embedded_map'

  get 'contributors' => 'contributors#show'
  match 'organisations/search' => 'organisations#search', via: [:get, :post]

  get '/organisation_reports/without_users' => 'organisation_reports#without_users_index', as: :organisations_report
  post '/invitations' => 'invitations#create', as: :invitations

  get '/user_reports/all' => 'user_reports#index', as: :users_report
  put '/user_reports/update' => 'user_reports#update', as: :user_report
  delete '/user_reports' => 'user_reports#destroy'
  get '/user_reports/invited' => 'user_reports#invited', as: :invited_users_report
  get '/user_reports/deleted' => 'user_reports#deleted', as: :deleted_users_report
  put 'user_reports/undo_delete/:id' => 'user_reports#undo_delete', as: :undo_delete_users_report

  resources :doit_organisations, only: [:index]
  resources :pages, only: [:index, :new, :create, :edit]
  resources :volunteer_ops, :only => [:index, :edit, :show, :update, :destroy] do
    get 'search', on: :collection
  end
  resources :proposed_organisation_edits, :only => [:index]
  resources :organisations do
    resources :volunteer_ops, :only => [:new, :create]
    resources :proposed_organisation_edits, :only => [:new, :show, :create, :update]
  end
  resources :users
  get 'events/search' => 'events#search'
  resources :events, :only => [:new, :create, :show, :index]
  resources :proposed_organisations, :only => [:new, :create, :show, :index, :update, :destroy]

  get ':id', to: 'pages#show', as: :page
  patch ':id', to: 'pages#update', as: nil
  delete ':id', to: 'pages#destroy', as: nil

  post 'cookies/allow', to: 'application#allow_cookie_policy'

  resources :mail_templates

  root :to => 'volunteer_ops#index'

end

app/models/base_organisation.rb
class BaseOrganisation < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  
  acts_as_paranoid
  validates_url :website, preferred_scheme: 'http://', message: 'Website is not a valid URL',
    if: proc{|org| org.website.present?}
  validates_url :donation_info, preferred_scheme: 'http://', message: 'Donation url is not a valid URL',
    if: proc{|org| org.donation_info.present?}
  validates :name, presence: { message: "Name can't be blank"}
  validates :description, presence: { message: "Description can't be blank"}
  has_many :category_organisations, :foreign_key => :organisation_id
  has_many :categories, :through => :category_organisations, :foreign_key => :organisation_id
  # For the geocoder gem
  geocoded_by :full_address
  after_validation :geocode, if: -> { run_geocode? }
  self.table_name = "organisations"

  def run_geocode?
    ## http://api.rubyonrails.org/classes/ActiveModel/Dirty.html
    address_changed? or postcode_changed? or (address.present? and not_geocoded?)
  end

  def not_geocoded?
    latitude.blank? and longitude.blank?
  end

  def full_address
     "#{self.address}, #{self.postcode}"
  end

  def gmaps4rails_marker_attrs
    if recently_updated_and_has_owner
      ['marker.png',
        'data-id' => id,
       class: 'marker']
    else
      ['measle.png',
        'data-id' => id,
        class: 'measle']
    end
  end

  def has_been_updated_recently?
    updated_at >= 1.year.ago
  end
  
  def slug_candidates
    SetupSlug.run(self.name) 
  end

end

app/models/organisation.rb
require 'csv'
require 'string'

class Organisation < BaseOrganisation

  has_many :volunteer_ops
  has_many :users
  has_many :edits, class_name: 'ProposedOrganisationEdit', :dependent => :destroy

  accepts_nested_attributes_for :users # TODO check if needed

  scope :order_by_most_recent, -> { order('organisations.updated_at DESC') }
  scope :not_null_email, lambda {where("organisations.email <> ''")}

  # Should we not use :includes, which pulls in extra data? http://nlingutla.com/blog/2013/04/21/includes-vs-joins-in-rails/
  # Alternative => :joins('LEFT OUTER JOIN users ON users.organisation_id = organisations.id)
  # Difference between inner and outer joins: http://stackoverflow.com/a/38578/2197402

  scope :null_users, lambda { includes(:users).where("users.organisation_id IS NULL").references(:users) }
  scope :without_matching_user_emails, lambda {where("organisations.email NOT IN (#{User.select('email').to_sql})")}

  after_save :uninvite_users, if: ->{ saved_change_to_attribute?(:email) }

  def uninvite_users
    users.invited_not_accepted.update_all(organisation_id: nil)
  end

  def update_attributes_with_superadmin(params)
    email = extract_email_from(params)
    return unless email.blank? || can_add_or_invite_admin?(email)
    self.update_attributes(params)
  end
  
  def rollback_acceptance
    org = becomes!(ProposedOrganisation)
    org.save!
    org
  end

  def self.search_by_keyword(keyword)
     keyword = "%#{keyword}%"
     where(contains_description?(keyword).or(contains_name?(keyword)))
  end

  def self.filter_by_categories(category_ids)
    joins(:categories)
      .where(category_id.in category_ids)                 # at this point, orgs in multiple categories show up as duplicates
      .group(organisation_id)                             # so we exploit this
      .having(organisation_id.count.eq category_ids.size) # and return the orgs with correct number of duplicates
  end

  #Edit this if CSV 'schema' changes
  #value is the name of a column in csv file
  @@column_mappings = {
      name: 'Title',
      address: 'Contact Address',
      description: 'Activities',
      website: 'website',
      telephone: 'Contact Telephone',
      date_removed: 'date removed',
      cc_id: 'Charity Classification'
  }

  def self.column_mappings
    @@column_mappings
  end

  def self.import_categories_from_array(row)
    check_columns_in(row)
    org_name = row[@@column_mappings[:name]].to_s.humanized_all_first_capitals
    org = Organisation.find_by_name(org_name)
    check_categories_for_import(row, org)
    org
  end

  def self.check_categories_for_import(row, org)
    category_ids = row[@@column_mappings[:cc_id]] if org
    category_ids.split(',').each do |id|
      cat = Category.find_by_charity_commission_id(id.to_i)
      org.categories << cat
    end if category_ids
  end

  def self.import_category_mappings(filename, limit)
    import(filename, limit, false) do |row, validation|
      import_categories_from_array(row)
    end
  end

  def self.create_from_array(row, validate)
    CreateOrganisationFromArray.create(Organisation, row, validate)
  end

  def self.create_and_validate(attributes)
    # create!(attributes.select{|k,v| !v.nil?})
    create!(attributes.each { |k, v| attributes[k] =v.nil? ? 'No information recorded' : (v.empty? ? 'No information recorded' : v) })
  end

  def self.create_and_substitute_with_empty(attributes)
    create!(attributes.each { |k, v| attributes[k] = v.empty? ? 'NO INFORMATION RECORDED' : v })
  end

  def self.import_addresses(filename, limit, validation = true)
    import(filename, limit, validation) do |row, validation|
       sleep 0.1
       create_from_array(row, validation)
    end
  end

  def self.import(filename, limit, validation, &block)
    csv_text = File.open(filename, 'r:ISO-8859-1')
    count = 0
    CSV.parse(csv_text, :headers => true).each do |row|
      break if count >= limit
      count += 1
      begin
        yield(row, validation)
      rescue CSV::MalformedCSVError => e
        logger.error(e.message)
      end
    end
  end

  def self.import_emails(filename, limit, validation = true)
    str = ''
    import(filename, limit, validation) do |row, validation|
      str << add_email(row, validation)
    end
    str
  end

  def self.add_email(row, validation)
    orgs = where("UPPER(name) LIKE ? ","%#{row[0].try(:upcase)}%")
    return "#{row[0]} was not found\n" unless orgs && orgs[0] && orgs[0].email.blank?
    orgs[0].email = row[7].to_s
    orgs[0].save
    return "#{row[0]} was found\n"
  end

  def self.check_columns_in(row)
    @@column_mappings.each_value do |column_name|
      unless row.header?(column_name)
        raise CSV::MalformedCSVError, "No expected column with name #{column_name} in CSV file"
      end
    end
  end

  private

  def embellish_invite_error_and_add_to_model(email, error_msg)
    error_msg = ("Error: Email is invalid" == error_msg) ? "The user email you entered,'#{email}', is invalid" : error_msg
    self.errors.add(:superadministrator_email, error_msg)
  end

  def add_and_notify(usr)
    self.users << usr
    org_admin_email = [usr.email]
    OrgAdminMailer.new_org_admin(self, org_admin_email).deliver_now
  end

  def can_add_or_invite_admin?(email)
    return false if email.blank?
    usr = User.find_by_email(email)
    return add_and_notify(usr) if usr.present?
    result = ::SingleInviteJob.new(self, email).invite_user
    return true if result.invited_user?
    embellish_invite_error_and_add_to_model(email,result.error)
    false
  end

  def extract_email_from(params)
    email = params[:superadmin_email_to_add]
    params.delete :superadmin_email_to_add
    email
  end

  def self.table
    arel_table
  end

  def self.organisation_id
    table[:id]
  end

  def self.category_table
    Category.arel_table
  end

  def self.category_id
    category_table[:id]
  end

  def self.contains_description?(key)
    table[:description].matches(key)
  end

  def self.contains_name?(key)
    table[:name].matches(key)
  end


end

app/controllers/organisations_controller.rb
class OrganisationsController < BaseOrganisationsController
  add_breadcrumb 'All Organisations', :organisations_path
  layout 'two_columns_with_map'
  # GET /organisations/search
  # GET /organisations/search.json
  before_action :authenticate_user!, :except => [:search, :index, :show]
  prepend_before_action :set_organisation, only: [:show, :update, :edit]

  def search
    @parsed_params = SearchParamsParser.new(params)
    @cat_name_ids = Category.name_and_id_for_what_who_and_how
    @organisations = Queries::Organisations.search_by_keyword_and_category(
      @parsed_params
    )
    flash.now[:alert] = SEARCH_NOT_FOUND if @organisations.empty?
    @markers = build_map_markers(@organisations)

    render :template =>'organisations/index'
  end

  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Queries::Organisations.order_by_most_recent
    @markers = build_map_markers(@organisations)
    @cat_name_ids = Category.name_and_id_for_what_who_and_how
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
    render template: 'pages/404', status: 404 and return if @organisation.nil?
    organisations = Organisation.where(id: @organisation.id)
    @user_opts = current_user ? get_user_options(@organisation) : {grabbable: true}
    @user_opts[:can_propose_edits] = current_user.present? && !@user_opts[:editable]
    @markers = build_map_markers(organisations)
    @cat_name_ids = Category.name_and_id_for_what_who_and_how
  end

  # GET /organisations/new
  # GET /organisations/new.json
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
    organisations = Organisation.where(id: @organisation.id)
    @markers = build_map_markers(organisations)
    return false unless user_can_edit? @organisation
    #respond_to do |format|
    #  format.html {render :layout => 'full_width'}
    #end
  end

  # POST /organisations
  # POST /organisations.json
  def create
    # model filters for logged in users, but we check here if that user is an superadmin
    # TODO refactor that to model responsibility?
    org_params = OrganisationParams.build params

    unless current_user.try(:superadmin?)
      flash[:notice] = PERMISSION_DENIED
      redirect_to organisations_path and return false
    end
    @organisation = Organisation.new(org_params)
    if @organisation.save
      redirect_to @organisation, notice: 'Organisation was successfully created.'
    else
     render :new
    end
  end

  # PUT /organisations/1
  # PUT /organisations/1.json
  def update
    params[:organisation][:superadmin_email_to_add] = params[:organisation_superadmin_email_to_add] if params[:organisation]
    update_params = OrganisationParams.build params
    return false unless user_can_edit? @organisation
    if @organisation.update_attributes_with_superadmin(update_params)
      redirect_to @organisation, notice: 'Organisation was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    unless current_user.try(:superadmin?)
      flash[:notice] = PERMISSION_DENIED
      redirect_to organisation_path(params[:id]) and return false
    end
    @organisation = Organisation.friendly.find(params[:id])
    @organisation.destroy
    flash[:success] = "Deleted #{@organisation.name}"

    redirect_to organisations_path
  end

  class OrganisationParams
    def self.build params
      params.require(:organisation).permit(
        :superadmin_email_to_add,
        :description,
        :address,
        :publish_address,
        :postcode,
        :email,
        :publish_email,
        :website,
        :publish_phone,
        :donation_info,
        :name,
        :telephone,
        category_ids: []
      )
    end

  end

  private

  def get_user_options(organisation)
      {
        pending_org_admin: current_user.pending_org_admin?(organisation),
        editable: current_user.can_edit?(organisation),
        deletable: current_user.can_delete?(organisation),
        can_create_volunteer_op: current_user.can_create_volunteer_ops?(organisation),
        grabbable: current_user.can_request_org_admin?(organisation)
      }
  end

  def set_organisation
    @organisation = Organisation.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    @organisation = nil
  end

  def user_can_edit?(org)
    unless current_user.try(:can_edit?,org)
      flash[:notice] = PERMISSION_DENIED
      redirect_to organisation_path(params[:id]) and return false
    end
    true
  end

  def meta_tag_title
    return super unless @organisation
    @organisation.name
  end

  def meta_tag_description
    return super unless @organisation
    @organisation.description
  end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
  
  def render_link_categories(type, org, &block)
    org.categories.send(:"#{type}").map(&block)
  end
  
  def params_hash(type, category)
    hash = { what_id: '', who_id: '', how_id: '', q: '' }
    hash[:"#{type.split(/_/).first}_id"] = category.id
    hash
  end

end

app/views/organisations/_category_type.erb
<div class="row category_type">
  <h5>What you do</h5>
  <%= f.collection_check_boxes( :category_ids, Category.what_they_do, :id, :name ) do |b| %>
    <div class="col-md-6 org-category">
      <%= b.label(class: 'checkbox inline') do %>
        <%= b.check_box %>
        <%= b.text %>
      <%end%>
    </div>
  <%end%>
</div>

<div class="row category_type">
  <h5>Who you help</h5>
  <%= f.collection_check_boxes( :category_ids, Category.who_they_help, :id, :name ) do |b|%>
    <div class="col-md-6 org-category">
      <%= b.label(class: 'checkbox inline') do %>
        <%= b.check_box %>
        <%= b.text %>
      <%end%>
    </div>
  <%end%>
</div>

<div class="row category_type">
  <h5>How you help</h5>
  <%= f.collection_check_boxes( :category_ids, Category.how_they_help, :id, :name ) do |b| %>
    <div class="col-md-6 org-category">
      <%= b.label(class: 'checkbox inline') do %>
        <%= b.check_box %>
        <%= b.text %>
      <%end%>
    </div>
  <%end%>
</div>

app/views/organisations/_form.html.erb
<%= form_for org do |f| %>
  <table>
    <thead>
    </thead>
    <tbody>
    <tr>
      <td data-toggle="tooltip" title="Enter a unique name">
        <% if org.errors[:name].any?%>
          <p class="error-name"><%= org.errors[:name].first %></p>
        <% end %>
        <%= f.text_area :name, :size => "50x4", :class => "wide_form org_h3", :placeholder => "Enter organisation name" %>
      </td>
      <td class="borderless">
        <input type="checkbox" class="publish" disabled checked = "checked" value="">
      </td>
    </tr>
    <tr>
      <td class="borderless" data-toggle="tooltip" title="Enter a full description here. When an individual searches this database all words in this description will be searched.">
        <% if org.errors[:description].any?%>
          <p class="error"><%= org.errors[:description].first %></p>
        <% end %>
        <%= f.text_area :description, :class => "wide_form", :cols => "10", :rows => "10", :placeholder => "Enter organisation description" %>
      </td>
      <td class="borderless">
        <input type="checkbox" class="publish" disabled checked = "checked" value="">
      </td>
    </tr>
    <tr><td><h3>
      Contact information
    </h3></td></tr>
    <tr>
      <td data-toggle="tooltip" title="Enter a complete address">
        <%= f.text_field :address, :class => "wide_form", :placeholder => "Enter organisation address"%>
      </td>
      <td class="borderless" data-toggle="tooltip" title="Toggle to change the visibility of your address">
        <%= f.check_box :publish_address, :class => 'publish' %>
      </td>
    </tr>
    <tr>
      <td class="borderless" data-toggle="tooltip" title="Make sure post code is accurate">
        <%= f.text_field :postcode, :class => "wide_form", :placeholder => "Enter organisation post code" %>
      </td>
      <td class="borderless">
        <input type="checkbox" class="publish" disabled checked = "checked" value="">
      </td>
    </tr>
    <tr>
      <td class="borderless" data-toggle="tooltip" title="Make sure email is correct">
        <%= f.text_field :email, :class => "wide_form", :placeholder => "Enter organisation email address" %>
      </td>
      <td class="borderless" data-toggle="tooltip" title="Toggle to change the visibility of your email address">
        <%= f.check_box :publish_email, :class => 'publish' %>
      </td>
    </tr>
    <tr>
      <td class="borderless" data-toggle="tooltip" title="Make sure url is correct">
        <% if org.errors[:website].any?%>
          <p class="error"><%= org.errors[:website].first %></p>
        <% end %>
        <%= f.text_field :website, :class => "wide_form", :placeholder => "Enter organisation website url" %>
      </td>
      <td class="borderless">
        <input type="checkbox" class="publish" disabled checked = "checked" value="">
      </td>
    </tr>
    <tr>
      <td class="borderless" data-toggle="tooltip" title="Make sure phone number is correct">
        <%= f.text_field :telephone, :class => "wide_form", :placeholder => "Enter organisation phone number" %>
      </td>
      <td class="borderless" data-toggle="tooltip" title="Toggle to change the visibility of your telephone number">
        <%= f.check_box :publish_phone, :class => "publish"%>
      </td>
    </tr>
    <tr>
      <td class="borderless" data-toggle="tooltip" title="Please enter a website here either to the fundraising page on your website or to an online donation site.">
        <% if org.errors[:donation_info].any?%>
          <p class="error"><%= org.errors[:donation_info].first %></p>
        <% end %>
        <%= f.text_field :donation_info, :class => "wide_form", :placeholder => "Enter organisation donation url" %>
      </td>
      <td class="borderless">
        <input type="checkbox" disabled checked = "checked" value="" class="publish">
      </td>
    </tr>
    <tr>
      <td class="borderless" >
        <div>
          <%= render partial: 'organisations/organisation_admin_display', locals: {org: org} %>
       </div>
      </td>
      <td class="borderless">
        <input type="checkbox" class="publish" disabled>
      </td>
    </tr>
  <tr>
    <td class="borderless" data-toggle="tooltip" title="Please enter the details of individuals from your organisation you would like to give permission to update your entry. E-mail addresses entered here will not be made public.">
      <%= text_field_tag 'organisation_superadmin_email_to_add', value = nil, {:size => 100, class: 'wide_form', :cols => "10", :rows => "3", :placeholder => 'You may add an organisation administrator email here'} %>
    </td>
    <td class="borderless"></td>
  </tr>
    </tbody>
  </table>
  <div class="org-categories">
    <h4>Edit categories</h4>
    <%= render partial: 'organisations/category_type', locals: {f: f} %>
  </div>
    <br>
    <% if org.class == ProposedOrganisation %>
        <h5>Please Confirm you are a not for profit organisation and are registered or working in Harrow</h5>
        <%= f.check_box :non_profit %>
        <%= f.label :non_profit ,"We are a not for profit organisation registered or working in Harrow", class: "checkbox inline", style: "padding-left: 5px; padding-top: 1px;" %>
    <% end %>

    <% if @user_id %>
      <%= f.hidden_field :user_id, value: @user_id %> 
    <%end %>

    <div id="org-cat-buttons" class="row">
      <div class="position-bottom col-md-6">
        <div class="actions">
          <%= f.submit :class => 'btn btn-primary' %>
        </div>
      </div>
    </div>

<% end %>

<% render partial: 'shared/map_scripts', locals: {markers: @markers} %>

app/views/organisations/_organisation_admin_display.erb
<% if org.users.empty? %>
  <div>This organisation has no admins yet</div>
<% else %>
  <div>
    Organisation administrator emails:
    <ul>
      <% org.users.each do |superadmin| %>
        <li><%= superadmin.email %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/organisations/_popup.html.erb
<button class='close infowindow_close' type='button'>×</button>
<%= link_to org['name'], organisation_path(org) %><br/>
<%= smart_truncate(org['description'], 44) %>

app/views/organisations/_search_form.html.erb
<%= form_tag(organisations_search_path, :id => "organisation_search", :method => "get") do %>
  <div class="flex-column">
    <div class="flex-row">
      <div class="left-side">
        <%= label_tag(:what_id, "What They Do", class: 'field-label') %>
      </div>
      <div class="right-side">
        <%= select_tag(:what_id, options_for_select(@cat_name_ids[:what], @parsed_params.try(:what_id)), { :include_blank => 'All' }) %>
      </div>
    </div>
    <div class="flex-row">
      <div class="left-side">
        <%= label_tag(:who_id, "Who They Help", class: 'field-label') %>
      </div>
      <div class="right-side">
        <%= select_tag(:who_id, options_for_select(@cat_name_ids[:who], @parsed_params.try(:who_id)), :include_blank => 'All' ) %>
      </div>
    </div>
    <div class="flex-row">
      <div class="left-side">
        <%= label_tag(:how_id, "How They Help", class: 'field-label') %>
      </div>
      <div class="right-side">
        <%= select_tag(:how_id, options_for_select(@cat_name_ids[:how], @parsed_params.try(:how_id)), { :include_blank => 'All' }) %>
      </div>
    </div>
    <div class="flex-row">
      <div class="left-side">
        <%= label_tag(:q, "Optional Search Text", class: 'field-label') %>
      </div>
      <div class="right-side">
        <%= text_field_tag(:q, @parsed_params.try(:query_term)) %>
        <%= submit_tag "Submit", { :class => 'btn btn-info' } %>
      </div>
    </div>
  </div>
<% end %>

app/views/organisations/_show.html.erb
<div id="org-information">
  <h2>
    <%= org.name %>
  </h2>

  <p>
    <%= simple_format org.description %>
  </p>

  <h3>
    Contact information
  </h3>
  <% if org.address.present? && (org.publish_address? || org.type == "ProposedOrganisation")%>
      <h4>Address: <span><%= org.address %></span></h4>
  <% end %>
  <% if org.postcode.present? %>
      <h4>Postcode: <span><%= org.postcode %></span></h4>
  <% end %>
  <% if org.email.present? && (org.publish_email? || org.type == "ProposedOrganisation")%>
      <h4>Email: <span><a href="mailto:<%= org.email %>"><%= org.email %></a></span></h4>
  <% end %>
  <% if org.website.present? %>
      <h4>Website: <span><%= link_to org.website, org.website, {:target => '_blank'} %></a></span></h4>
  <% end %>
  <% if org.telephone.present? && (org.publish_phone? || org.type == "ProposedOrganisation")%>
      <h4>Telephone: <span><%= org.telephone %></span></h4>
  <% end %>
  <% if org.donation_info.present? %>
      <h4>Donation Info: <span><%= link_to "Donate to #{org.name} now!", org.donation_info, {:target => '_blank'} %></span></h4>
  <% end %>

   <div id="org-categories">
    <% if org.categories.present? %>
      <h4>Categories: </h4>
      <ul class="org-categories">
        <% ['what_they_do', 'who_they_help', 'how_they_help'].each do |type| %>
          <li id=<%="#{type}"%> >
            <h5><strong><%="#{type.capitalize.gsub(/_/, ' ')}"%></strong></h5>
            <p>
            <%= safe_join(render_link_categories(type, org) {|category| link_to category.name, 
            organisations_search_path(params_hash(type,category))}, ', ') %>
            </p>
          </li>
        <% end %>

      </ul>
    <% end %>
   </div>

</div>

app/views/organisations/edit.html.erb
<%= render partial: 'form', locals: {org: @organisation} %>

app/views/organisations/index.html.erb
<div>
  <h1>Harrow Community Network</h1>
  <p>Harrow Community Network is a service provided by Voluntary Action Harrow Cooperative to help local residents and organisations to discover volunteer opportunities in the Harrow area.</p>
</div>
<%= render partial: 'search_form' %>

<div id="orgs_scroll">
  <div class="table">
    <table>
      <% @organisations.each do |organisation| %>
        <tr>
          <td>
            <u><%= link_to organisation.name, organisation, { :target => '_blank' } %></u><br/>
            <%= smart_truncate(organisation.description) %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div style="width:50%;float:left">
  <%= link_to_if(current_user.try(:superadmin?), 'Add Organisation',
                 new_organisation_path){} %>
</div>

<% render partial: 'shared/map_scripts', locals: {markers: @markers} %>

<% render 'shared/map_legend_script' %>

app/views/organisations/new.html.erb
<h1>New organisation</h1>

<%= render partial: 'form', locals: {org: @organisation} %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<% content_for :scripts do %>
    <%= javascript_include_tag 'this_is_my_org' %>
<% end %>

<% if feature_active? :search_input_bar_on_org_pages %>
  <%= render partial: "search_form" %>
<% end %>
<%= render partial: "show", locals: {org: @organisation} %>
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<div class="addthis_inline_share_toolbox"></div>

<div id="org-cat-buttons" class="row">
  <div class="position-bottom col-md-6">
    <% if @user_opts[:editable] %>
        <%= link_to("Edit", edit_organisation_path(@organisation), {:class => 'btn btn-primary'}) %>
    <% end %>
    <% if @user_opts[:can_propose_edits] %>
        <%= link_to("Propose an edit", new_organisation_proposed_organisation_edit_path(@organisation) , {:class => 'btn btn-primary'})%>
    <% end %>
    <% if @user_opts[:deletable] %>
        <%= link_to("Delete", organisation_path(@organisation), {method: :delete, :class => 'btn btn-danger'}) %>
    <% end %>
    <% if @user_opts[:can_create_volunteer_op] and feature_active?(:volunteer_ops_create) %>
        <%= link_to("Create a Volunteer Opportunity", new_organisation_volunteer_op_path(organisation_id: @organisation), {:class => 'btn btn-primary'}) %>
    <% end %>
    <% if current_user %>
        <%= link_to "This is my organisation", user_path(pending_organisation_id: @organisation, id: current_user.id), {method: :put, class: 'btn btn-primary'} if @user_opts[:grabbable] %>
    <% else %>
        <%= link_to "This is my organisation", new_user_session_path, {method: :put, 'data-signed_in' => current_user.present?, id: 'TIMO', class: 'btn btn-primary'} if @user_opts[:grabbable] %>
    <% end %>
    <% if @user_opts[:pending_org_admin] %>
      <p class="org-info-msg-1" ><strong>Your request for admin status is pending.</strong></p>
    <% end%>
  </div>
</div>

<% render partial: 'shared/map_scripts', locals: {markers: @markers} %>
<% render partial: 'shared/addthis_scripts' %>

app/views/organisations/without_users_index.html.erb
<table class="table table-hover sortable">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th style="text-align: center;"></th>
  </tr>
  </thead>
  <tbody>
  <% @organisations.each do |organisation| %>
      <tr id="<%= organisation.id %>">
        <td><%= link_to organisation.name, organisation_path(organisation) %></td>
        <td><%= organisation.email %></td>
        <td class="response" style="text-align: center;">
          <input type="checkbox" data-id="<%= organisation.id %>" data-email="<%= organisation.email %>"/>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>