config/routes.rb
LocalSupport::Application.routes.draw do

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  get '/embedded/map' => 'volunteer_ops#embedded_map'

  get 'contributors' => 'contributors#show'
  match 'organisations/search' => 'organisations#search', via: [:get, :post]

  get '/organisation_reports/without_users' => 'organisation_reports#without_users_index', as: :organisations_report
  post '/invitations' => 'invitations#create', as: :invitations

  get '/user_reports/all' => 'user_reports#index', as: :users_report
  put '/user_reports/update' => 'user_reports#update', as: :user_report
  delete '/user_reports' => 'user_reports#destroy'
  get '/user_reports/invited' => 'user_reports#invited', as: :invited_users_report
  get '/user_reports/deleted' => 'user_reports#deleted', as: :deleted_users_report
  put 'user_reports/undo_delete/:id' => 'user_reports#undo_delete', as: :undo_delete_users_report

  resources :doit_organisations, only: [:index]
  resources :pages, only: [:index, :new, :create, :edit]
  resources :volunteer_ops, :only => [:index, :edit, :show, :update, :destroy] do
    get 'search', on: :collection
  end
  resources :proposed_organisation_edits, :only => [:index]
  resources :organisations do
    resources :volunteer_ops, :only => [:new, :create]
    resources :proposed_organisation_edits, :only => [:new, :show, :create, :update]
  end
  resources :users
  get 'events/search' => 'events#search'
  resources :events, :only => [:new, :create, :show, :index]
  resources :proposed_organisations, :only => [:new, :create, :show, :index, :update, :destroy]

  get ':id', to: 'pages#show', as: :page
  patch ':id', to: 'pages#update', as: nil
  delete ':id', to: 'pages#destroy', as: nil

  post 'cookies/allow', to: 'application#allow_cookie_policy'

  resources :mail_templates

  root :to => 'volunteer_ops#index'

end

app/models/volunteer_op.rb
class VolunteerOp < ActiveRecord::Base
  include GlobalID::Identification
  acts_as_paranoid
  validates :title, :description, presence: true
  validates :organisation_id, presence: true, if: "source == 'local'"
  belongs_to :organisation
  has_one :doit_trace

  geocoded_by :full_address
  after_validation :geocode, if: :address_complete?
  after_validation :clear_lat_lng, if: "source == 'local'"

  scope :order_by_most_recent, -> { order('updated_at DESC') }
  scope :local_only,           -> { where(source: 'local') }
  scope :doit,                 -> { where(source: 'doit') }
  scope :reachskills,          -> { where(source: 'reachskills') }
  scope :remote_only,          -> { where.not(source: 'local') }

  def self.add_coordinates(vol_ops)
    vol_op_with_coordinates(vol_ops)
  end

  def full_address
    "#{self.address}, #{self.postcode}"
  end

  def organisation_name
    return organisation.name if source == 'local'
    return doit_org_name if source == 'doit'
    reachskills_org_name
  end

  def organisation_link
    return organisation if source == 'local'
    return "https://do-it.org/organisations/#{doit_org_link}" if source == 'doit'
    "https://reachskills.org.uk/org/#{parsed_reachskills_org_name}"
  end

  def link
    return self if source == 'local'
    return "https://do-it.org/opportunities/#{doit_op_id}" if source == 'doit'
    reachskills_op_link
  end

  def self.search_for_text(text)
    keyword = "%#{text}%"
    where(contains_description?(keyword).or(contains_title?(keyword)))
  end

  def self.contains_description?(text)
    arel_table[:description].matches(text)
  end

  def self.contains_title?(text)
    arel_table[:title].matches(text)
  end

  def self.build_by_coordinates(vol_ops = nil)
    if vol_ops.nil?
      local_vol_ops = vol_op_with_coordinates(VolunteerOp.local_only)
      vol_ops = local_vol_ops + VolunteerOp.remote_only
    else
      vol_ops = vol_op_with_coordinates(vol_ops)
    end
    Location.build_hash(group_by_coordinates(vol_ops))
  end

  def address_complete?
    address.present? && postcode.present?
  end

  def self.get_source(volunteer_ops)
    source = volunteer_ops.first.source
    unless volunteer_ops.all? { |vol_op| vol_op.source == source }
      source = 'mixed'
    end
    source
  end

  def new?
    one_day_ago = Time.current - 1.day
    created_at > one_day_ago
  end

  private

  def clear_lat_lng
    return if address_complete?
    self.longitude = nil
    self.latitude = nil
  end

  def self.vol_op_with_coordinates(vol_ops)
    vol_ops.map { |op| op.source == 'local' ? op.send(:lat_lng_supplier) : op }
  end

  def lat_lng_supplier
    return self if latitude && longitude
    send(:with_organisation_coordinates)
  end

  def with_organisation_coordinates
    self.tap do |v|
      v.longitude = v.organisation.longitude
      v.latitude = v.organisation.latitude
    end
  end

  def self.group_by_coordinates(vol_ops)
    vol_ops.group_by do |vol_op|
      [vol_op.longitude, vol_op.latitude]
    end
  end

  def parsed_reachskills_org_name
    reachskills_org_name.downcase.gsub(' ', '-')
  end

end

app/models/volunteer_op_form.rb
class VolunteerOpForm
  include ActiveModel::Model

  class DoitVolunteerOp
    include ActiveModel::Model
    
    validates :advertise_start_date, presence: true
    validates :advertise_end_date, presence: true
    validates :doit_org_id, presence: true
    attr_accessor :advertise_start_date, :advertise_end_date, :doit_org_id

  end

  attr_accessor :volunteer_op, :post_to_doit, :doit_volunteer_op

  validate :validate_children

  def volunteer_op
    @volunteer_op ||= VolunteerOp.new
  end

  def doit_volunteer_op
    @doit_volunteer_op ||= DoitVolunteerOp.new
  end

  def post_to_doit
    @post_to_doit ||= 0
  end

  def self.volunteer_op_attributes
    VolunteerOp.column_names.push(VolunteerOp.reflections.keys).flatten
  end

  def self.doit_volunteer_op_attributes
    [:advertise_start_date, :advertise_end_date, :doit_org_id]
  end

  volunteer_op_attributes.each do |attr|
    delegate attr.to_sym, "#{attr}=".to_sym, to: :volunteer_op
  end

  doit_volunteer_op_attributes.each do |attr|
    delegate attr.to_sym, "#{attr}=".to_sym, to: :doit_volunteer_op
  end

  delegate :id, :persisted?, :new_record?, to: :volunteer_op

  def self.model_name
    new.volunteer_op.model_name
  end

  def assign_attributes(params)
    volunteer_op_params = params.slice(*self.class.volunteer_op_attributes) 
    volunteer_op.assign_attributes(volunteer_op_params)
    @post_to_doit = params[:post_to_doit]
    doit_volunteer_op_params = params.slice(*self.class.doit_volunteer_op_attributes) 
    @doit_volunteer_op = DoitVolunteerOp.new(doit_volunteer_op_params)
  end

  def save
    return false unless valid?
    volunteer_op.save!
    PostToDoitJob.perform_later(build_options) if post_to_doit?
    true
  end

  private

  def post_to_doit?
    post_to_doit == '1'
  end

  def build_options
    {
      volunteer_op: volunteer_op,
      advertise_start_date: advertise_start_date,
      advertise_end_date: advertise_end_date,
      doit_org_id: doit_org_id
    }
  end

  def validate_children
    promote_errors(volunteer_op.errors) if volunteer_op.invalid?
    promote_errors(doit_volunteer_op.errors) if valid_doit_post?
  end

  def valid_doit_post?
    post_to_doit? && doit_volunteer_op.invalid?
  end

  def promote_errors(child_errors)
    child_errors.each do |attribute, message|
      errors.add(attribute, message)
    end
  end
end

app/controllers/volunteer_ops_controller.rb
class VolunteerOpsController < ApplicationController
  add_breadcrumb 'Volunteers', :root_url
  layout 'two_columns_with_map', except: :embedded_map
  before_action :set_organisation, only: [:new, :create]
  before_action :authorize, except: [:search, :show, :index, :embedded_map]
  prepend_before_action :set_volunteer_op, only: [:show, :edit]

  def search
    @query = params[:q]
    @volunteer_ops = VolunteerOp.order_by_most_recent.search_for_text(@query)
    flash.now[:alert] = SEARCH_NOT_FOUND if @volunteer_ops.empty?
    @markers = BuildMarkersWithInfoWindow
                   .with(VolunteerOp.build_by_coordinates(@volunteer_ops), self)
    render template: 'volunteer_ops/index'
  end

  def index
    @volunteer_ops = displayed_volunteer_ops
    @markers = BuildMarkersWithInfoWindow.with(VolunteerOp.build_by_coordinates, self)
  end

  def show
    render template: 'pages/404', status: 404 and return if @volunteer_op.nil?
    @organisation = Organisation.friendly.find(@volunteer_op.organisation_id)
    @editable = current_user.can_edit?(@organisation) if current_user
    @markers = BuildMarkersWithInfoWindow.with(VolunteerOp.build_by_coordinates, self)
    add_breadcrumb @organisation.name, organisation_path(@organisation)
    add_breadcrumb @volunteer_op.title, :volunteer_op_path
  end

  def new
    @volunteer_op = VolunteerOpForm.new
    @can_publish_to_doit = true if current_user.superadmin?
  end

  def create
    params[:volunteer_op][:organisation_id] = @organisation.id
    @volunteer_op = VolunteerOpForm.new(volunteer_op_params)
    result = @volunteer_op.save
    result ? vol_op_redirect(t('volunteer.create_success')) : render(:new)
  end

  def edit
    volunteer_op_record = VolunteerOp.find(params[:id])
    @can_publish_to_doit = true if can_post_to_doit?(volunteer_op_record.id)
    @volunteer_op = VolunteerOpForm.new(volunteer_op: volunteer_op_record )
    organisations = Organisation.where(id: @volunteer_op.organisation_id)
    @organisation = organisations.first!
    @markers = BuildMarkersWithInfoWindow.with(VolunteerOp.build_by_coordinates, self)
  end

  def update
    volunteer_op_record = VolunteerOp.find(params[:id])
    @volunteer_op = VolunteerOpForm.new(volunteer_op: volunteer_op_record )
    @organisation = @volunteer_op.organisation
    @volunteer_op.assign_attributes(volunteer_op_params)
    result = @volunteer_op.save
    result ? vol_op_redirect(t('volunteer.update_success')) : render(action: 'edit')
  end

  def destroy
    @volunteer_op = VolunteerOp.find(params[:id])
    @volunteer_op.destroy
    flash[:success] = "Deleted #{@volunteer_op.title}"
    redirect_to volunteer_ops_path
  end

  def embedded_map
    @markers = BuildMarkersWithInfoWindow.with(VolunteerOp.build_by_coordinates, self)
    response.headers.delete 'X-Frame-Options'
    render layout: false
  end

  def volunteer_op_params
    args = [:description, :title, :organisation_id, :address, :postcode,
            :post_to_doit, :advertise_start_date, :advertise_end_date,
            :doit_org_id ]
    params.require(:volunteer_op).permit(*args)
  end

  private

  def displayed_volunteer_ops
    vol_ops = VolunteerOp.order_by_most_recent.send(restrict_by_feature_scope)
    VolunteerOp.add_coordinates(vol_ops)
  end

  def restrict_by_feature_scope
    if Feature.active?(:doit_volunteer_opportunities) &&
       Feature.active?(:reachskills_volunteer_opportunities)
      return :all
    end
    return :doit if Feature.active?(:doit_volunteer_opportunities)
    return :reachskills if Feature.active?(:reachskills_volunteer_opportunities)
    :local_only
  end

  def authorize
    return if org_owner?
    flash[:error] = t('authorize.org_owner_or_superadmin')
    redirect_to '/' and return
  end

  def org_owner?
    current_user.present? && (current_user.can_edit? org_independent_of_route)
  end

  def org_independent_of_route
    organisation_set_for_nested_route? || organisation_for_simple_route
  end

  def organisation_set_for_nested_route?
    @organisation
  end

  def organisation_for_simple_route
    VolunteerOp.find(params[:id]).organisation
  end

  def organisation_for_nested_route
    Organisation.friendly.find(params[:organisation_id])
  end

  def set_organisation
    @organisation = organisation_for_nested_route
  end

  def set_volunteer_op
    @volunteer_op = VolunteerOp.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    @volunteer_op = nil
  end

  def vol_op_redirect(notice)
    redirect_to(@volunteer_op, notice: notice)
  end

  def meta_tag_title
    return super unless @volunteer_op
    @volunteer_op.title
  end

  def meta_tag_description
    return super unless @volunteer_op
    @volunteer_op.description
  end

  def can_post_to_doit?(vol_op_id)
    current_user.superadmin? && !DoitTrace.published?(vol_op_id)

  end
end

app/helpers/volunteer_ops_helper.rb
module VolunteerOpsHelper
  def button_text object
    object.new_record? ? 'Create a Volunteer Opportunity' : 'Update Volunteer Opportunity'
  end

  def link_to_vol_op(obj, type, html_options = {})
    html_options[:target] = '_blank' unless obj.source == 'local'
    return link_to(obj.title, obj.link, html_options) if type == :title
    link_to(obj.organisation_name, obj.organisation_link, html_options)
  end
end

app/views/volunteer_ops/_form.html.erb
<%= form_for(@volunteer_op, url: submission_url ) do |f| %>
  <% if @volunteer_op.errors.any? %>
    <div class= "text-danger", id="error_explanation">
      <%= pluralize(@volunteer_op.errors.count, "error") %> prohibited this volunteer_op from being saved:
      <ul>
        <% @volunteer_op.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :title, :style => "margin-top: 16px;" %>
    <%= f.text_field :title, class: "form-control" %>


    <%= f.label :description , :style => "margin-top: 16px;" %>
    <%= f.text_area :description, class: "form-control" %>


    <%= f.label :address , 'Address', :style => "margin-top: 16px;" %>
    <%= f.text_field :address, class: "form-control",
                  placeholder: "#{@organisation.address}" %>


    <%= f.label :postcode , 'Postcode', :style => "margin-top: 16px;" %>
    <%= f.text_field :postcode, class: "form-control",
                   placeholder: "#{@organisation.postcode}"%>

  <div class="checkbox-inline">
    <%= f.check_box :post_to_doit, id: 'check_to_doit' ,disabled: !@can_publish_to_doit %>
    <%= f.label :post_to_doit %>
  </div>
  <div id="doit_form">
    <div class="form-group">
      <%= f.label :doit_org_id, 'Doit organisation' %>
      <div id="doit_org_list">
        <i class="fa fa-spinner fa-spin fa-fw"></i>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :advertise_start_date %>
      <div class="input-group date">
        <%= f.text_field :advertise_start_date, class: 'form-control' %>
        <span class="input-group-addon" >
          <i class="fa fa-calendar" aria-hidden="true"></i>
        </span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :advertise_end_date %>
      <div class="input-group date">
        <%= f.text_field :advertise_end_date, class: 'form-control'%>
        <span class="input-group-addon" >
          <i class="fa fa-calendar" aria-hidden="true"></i>
        </span>
      </div>
    </div>
  </div>
  <div class="actions" style="margin-top: 16px;">
    <%= f.submit button_text(@volunteer_op), class: 'btn btn-primary' %>
  </div>
<% end %>
<% render partial: 'shared/map_scripts', locals: {markers: markers} %>

app/views/volunteer_ops/_popup2.html.erb
<button class='close infowindow_close' type='button'>×</button>

Test

app/views/volunteer_ops/_popup_harrow.html.erb
<button class='close infowindow_close' type='button'>×</button>
<%= link_to org.name, org, :style => "font-weight: 100" %></strong></br>
<ul>
<% VolunteerOp.where(organisation_id: org.id).each do |op| %>
  <li>
    <%= link_to op.title, op, :style => "font-weight: 900" %></br>
    <%= smart_truncate(op.description,44) %></br>
  </li>
  <% end %>
  </ul>
</div>

app/views/volunteer_ops/_search_form.html.erb
<%= form_tag(search_volunteer_ops_path, :method => "get", class: "volunteer-ops-search") do %>
  <div class="flex-row">
    <div class="left-side">
        <%= label_tag(:q, "Search Text", class: 'field-label') %>
    </div>
    <div class="right-side">
        <%= text_field_tag(:q, @query, class: 'search-text') %>
        <%= submit_tag("Search", class: 'btn btn-info search-btn') %>
    </div>
  </div>
<% end %>

app/views/volunteer_ops/_volunteer_op.html.erb
<h3>
  <%= volunteer_op.title %>
</h3>

<p>
<%= simple_format auto_link volunteer_op.description %>
</p>

<% if volunteer_op.address_complete? %>
  <p>
  <b>Volunteer opportunity location:</b>
  <%= "#{ volunteer_op.address }, #{ volunteer_op.postcode }" %>
  </p>
<% end %>

<p>
<b>Organisation:</b>
<%= link_to volunteer_op.organisation.name, organisation_path(volunteer_op.organisation) %>
</p>

app/views/volunteer_ops/edit.html.erb
<%= render partial: 'form', locals: {submission_url: volunteer_op_path(@volunteer_op.id), markers: @markers} %>

app/views/volunteer_ops/embedded_map.erb
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Harrow Community Network | Harrow volunteering</title>
  <meta name="description" content="Volunteering Network for Harrow Community" />
  <link rel="author" href="http://www.agileventures.org" />

  <link rel="stylesheet" media="screen" href="/assets/application.css?body=1" />
  <link rel="stylesheet" media="screen" href="/assets/bootstrap_and_overrides.css?body=1" />
  <link rel="stylesheet" media="screen" href="/assets/gmaps.css?body=1" />


  <!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
  <script src="/assets/jquery.js?body=1"></script>
  <script src="/assets/underscore.js?body=1"></script>
  <script src="https://maps.google.com/maps/api/js?v=3&amp;libraries=geometry<%= gmap_key_value_for_url %>" type="text/javascript"></script>
  <%= javascript_include_tag 'maps' %>
</head>

<body>
  <div class="map_container"
       style="position:fixed; top:0; left:0; bottom:0; right:0; overflow: hidden; border:none; margin:0;">
    <%= content_tag "div", "", id: "marker_data", data: {markers: @markers} %>
    <div id="map-canvas" style="height:100%; width=100%;">
    </div>
  </div>
</body>
</html>

app/views/volunteer_ops/index.html.erb
<div>
  <h1>Harrow Volunteering Opportunities</h1>
</div> 
<%= render 'search_form' %>
<br>
<div id='orgs_scroll' style="height:410px;width:100%;border:1px solid #ccc;overflow:scroll;">
  <div class='table table-bordered'>
    <table>
      <% @volunteer_ops.each do |op| %>
          <tr>
            <td class='center-map-on-op'
                data-lat="<%= op.latitude %>" 
                data-lng="<%= op.longitude %>"  >
              <strong>
                <%= link_to_vol_op(op, :title) %>
              </strong><br/>
              <div id='organisations'>
                <small><%= link_to_vol_op(op, :organisation) %></small>
                <br/>
              </div>
              <%= smart_truncate(op.description) %>
              <br/>
            </td>
          </tr>
      <% end %>
    </table>
    <br>
  </div>
</div>
<% render partial: 'shared/map_scripts', locals: {markers: @markers} %>

<% render 'shared/map_legend_doit_script' %>

app/views/volunteer_ops/new.html.erb
<h3>Create a new Volunteer Opportunity</h3>
<%= render partial: 'form', locals: {submission_url: organisation_volunteer_ops_path(params[:organisation_id]), markers: nil} %>

app/views/volunteer_ops/show.html.erb
<%= render "search_form" %>
<%= render @volunteer_op %>
<% if @editable %>
  <%= link_to("Edit", edit_volunteer_op_path(@volunteer_op.id), {:class => 'btn btn-primary'}) %>
  <%= link_to("Delete", volunteer_op_path(@volunteer_op.id), {method: :delete, :class => 'btn btn-danger'}) %>
<% end %>

<% render partial: 'shared/map_scripts', locals: {markers: @markers} %>